branches:
  - master

tagFormat: "${version}"

preset: "conventionalcommits"

plugins:
  - "@semantic-release/commit-analyzer"
  - "semantic-release-commitlint"
  - "@semantic-release/release-notes-generator"
  -
    - "@semantic-release/git"
    - assets: []
      messsage: false
  -
    - "@semantic-release/github"
    - successComment: false
      failComment: false
  -
    - '@eshepelyuk/semantic-release-helm-oci'
    - registry: oci://ghcr.io/eshepelyuk
      skipAppVersion: true
  -
    - "@semantic-release/exec"
    - publishCmd: "skaffold build -t ${nextRelease.version}"
