= Contributing

== Requirements

This repository uses https://www.conventionalcommits.org/en/v1.0.0/[Conventional Commits]
for creating commit messages.

Please use following _types_ to create your commits:

* `feat`, for a new functionality.
* `fix`, for a bug fixes.
* `chore`, for everything else ( CI/CD, docs, etc)

Also, we would like PRs to contain a single commit and be rebased onto main project `master` branch before submitting.

== Git flow.

Although, you could choose your own approach to create branches, develop code
and provide new PR, we recommend following.

. Fork this project and clone it to local PC.

. Add this project as a new remote named `upstream`.
+
[source,bash]
----
$ git remote add upstream https://github.com/eshepelyuk/cmak-operator.git
$ git fetch upstream
----

. Create a new branch, based on `upstream` master and push it to your repository.
+
[source,bash]
----
$ git checkout --no-track -b my-branch upstream/master
$ git push -u origin my-branch
----

. Develop your code locally, test and commit.
+
[source,bash]
----
$ git commit -am '.....'
----

. Before pushing code to `origin` ensure your working branch is rebased onto `upstream/master`.
+
[source,bash]
----
$ git fetch upstream
$ git rebase -i upstream/master
----
+
During rebase, make your PR to be comprised of a single commit,
unless, you _really_ want to provide multiple commits via single PR.

. Push your branch and create a PR via GitHub UI.
+
[source,bash]
----
$ git push -u -f origin my-branch
----

