= CMAK operator
:toc: macro
:icons: font
:toclevels: 1

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

image:https://img.shields.io/github/v/tag/eshepelyuk/cmak-operator?logo=github&sort=semver&style=for-the-badge&label=current[Release,
link="https://github.com/eshepelyuk/cmak-operator/releases/latest"]
image:https://img.shields.io/docker/pulls/eshepelyuk/cmak-operator-cli?logo=docker&style=for-the-badge[Docker Hub,
link="https://hub.docker.com/repository/docker/eshepelyuk/cmak-operator-cli"]
image:https://img.shields.io/endpoint?style=for-the-badge&url=https://artifacthub.io/badge/repository/cmak-operator[Artifact
HUB, link="https://artifacthub.io/packages/helm/cmak-operator/cmak-operator"]
image:https://img.shields.io/github/license/eshepelyuk/cmak-operator?logo=mit&style=for-the-badge[MIT licence,
link="https://opensource.org/licenses/MIT", window="_blank"]

toc::[]

CMAK operator is a set of tools packaged as Helm chart, that allows to install
and configure https://github.com/yahoo/CMAK[CMAK]
(previously Kafka Manager) into Kubernetes cluster.

https://github.com/yahoo/CMAK[CMAK] (previously Kafka Manager)
is well-known and mature tool for monitoring and managing
https://kafka.apache.org/[Apache Kafka] clusters.

== Installation

CMAK operator could be installed only with https://helm.sh/docs/[Helm 3].
Helm chart is published to public Helm repository, hosted on GitHub itself.

It's recommended to install CMAK operator into a dedicated namespace.

[source]
.Add Helm repository
----
$ helm repo add cmak https://eshepelyuk.github.io/cmak-operator
$ helm repo update
----

[source]
.Install latest version
----
$ helm install --create-namespace -n cmak-ns mycmak cmak/cmak-operator
----

[source]
.Seach for available versions
----
$ helm search repo cmak-operator --versions
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
cmak/cmak-operator      0.2.1           3.0.0.5         CMAK operator for K8S.
cmak/cmak-operator      0.2.0           3.0.0.5         CMAK operator for K8S.
----

[source]
.Install specific version
----
$ helm install --create-namespace -n cmak-ns --version 0.2.1 mycmak cmak/cmak-operator
----

=== Verify installation

[IMPORTANT]
.Exposing CMAK UI
====
By default, CMAK operator doesn't create neither `Ingress`
nor any other K8S resources to expose UI via HTTP.
====

The simpliest test is to port forward CMAK UI HTTP port and access it from browser .

[source]
----
$ kubectl port-forward -n cmak-ns service/cmak 9000:9000
----

Then, open http://localhost:9000 in your browser.

== Configuration

=== CMAK application

CMAK uses configuration file
https://github.com/yahoo/CMAK/blob/master/conf/application.conf[/cmak/conf/application.conf].
Every parameter could be overriden via JVM system property, i.e. `-DmyProp=myVal`.
Properties are passed to CMAK container via `values.yaml`.

For example to enable basic auth add following

[source,yaml]
.values.yaml
----
ui:
  extraArgs:
  - "-DbasicAuthentication.enabled=true"
  - "-DbasicAuthentication.username=admin"
  - "-DbasicAuthentication.password=password"
----

=== Kafka clusters

It's extremely easy to configure multiple clusters in CMAK,
starting from cluster setup, connection settings and ending with authorization
using https://helm.sh/docs/chart_template_guide/values_files/[Helm values files].

Check https://artifacthub.io/packages/helm/cmak-operator/cmak-operator?modal=values-schema[CMAK operator values]
for all available options and their description.

. Minimal values.yaml configuration for adding a several Kafka clusters to CMAK.
[source,yaml]
----
cmak:
  clusters:
    - name: "cluster-stage"
      curatorConfig:
        zkConnect: "kafka01.stage:2181,kafka02.stage:2181"
    - name: "cluster-prod"
      curatorConfig:
        zkConnect: "kafka01.prod:2181,kafka02.prod:2181,kafka03.prod:2181"
----

Connection settings could be configured for all clusters at once or per dedicated cluster.

. Configuring connection settings
[source,yaml]
----
cmak:
  clustersCommon:
    curatorConfig:
      zkMaxRetry: 100 # <1>
  clusters:
    - name: "cluster-stage"
      kafkaVersion: "2.5.0" # <2>
      curatorConfig:
        zkConnect: "kafka01.stage:2181,kafka02.stage:2181"
    - name: "cluster-prod"
      kafkaVersion: "2.1.0" # <3>
      enabled: false
      curatorConfig:
        zkConnect: "kafka01.prod:2181,kafka02.prod:2181,kafka03.prod:2181"
----
<1> this setting is applied to both clusters.
<2> applied only to `cluster-stage`.
<3> applied only to `cluster-prod`.

Configuration should be passed to helm via command line during installation or upgrade.

[source]
[subs="attributes"]
----
$ helm install --create-namespace -n cmak-ns -f cmak-values.yaml mycmak cmak/cmak-operator
----

== Architecture

ifndef::env-github[]
plantuml::arch.puml[]
endif::env-github[]

ifdef::env-github[]
image::http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/eshepelyuk/cmak-operator/master/arch.puml[Component diagram]
endif::env-github[]

CMAK operator comprises following components:

* https://github.com/yahoo/CMAK/[CMAK],
  powered by https://hub.docker.com/r/hlebalbau/kafka-manager/[Docker image]
  from https://github.com/hleb-albau/kafka-manager-docker[@hleb-albau].
* https://zookeeper.apache.org/[Apache ZooKeeper],
  powered by https://hub.docker.com/_/zookeeper/[official Docker image].
* https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/[K8S CronJob]
  used to configure Kafka clusters,
  powered by
  https://hub.docker.com/repository/docker/eshepelyuk/cmak-operator-cli[custom Docker image].

Following desing choices were made.

=== Dedicated Zookeeper instance.

TO BE DEFINED.

=== Not using REST for configuring CMAK clusters.

TO BE DEFINED.

=== Reconciliation with CronJob.

TO BE DEFINED.

== Troubleshooting

CMAK doesn't configure clusters from Helm values::
+
* CMAK settings are not applied immediately, but only after `reconcile.schedule` period had passed.
* Check logs of cron job to see if there's no connection failure to ZK.
