apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: cmak-operator
build:
  artifacts:
  - image: eshepelyuk/json2zk
  local:
    push: true
profiles:
- name: local
  activation:
  - command: run
  - command: dev
  deploy:
    helm:
      releases:
      - name: cmak-operator
        chartPath: .
        wait: true
        valuesFiles:
        - values-dev.yaml
        artifactOverrides:
          image: eshepelyuk/json2zk
        imageStrategy:
          helm: {}
  portForward:
  - resourceType: Service
    resourceName: cmak
    port: 2181
  - resourceType: Service
    resourceName: cmak
    port: 9000
