apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: cmak-operator
build:
  artifacts:
    - image: eshepelyuk/cmak2zk
      context: ./cmak2zk
  local:
    push: true
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: cmak-operator
        chartPath: .
        wait: true
        setValues:
          e2e: true
        valuesFiles:
          - "test/e2e/{{.E2E_TEST}}/values.yaml"
        upgradeOnChange: false
        skipBuildDependencies: true
        artifactOverrides:
          image: eshepelyuk/cmak2zk
        imageStrategy:
          helm: {}
