apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: cmak-operator
build:
  artifacts:
  - image: eshepelyuk/json2zk
  local:
    push: true
profiles:
- name: local
  activation:
  - command: run
  - command: dev
  - command: delete
  deploy:
    helm:
      releases:
      - name: cmak-operator
        chartPath: .
        wait: true
        valuesFiles:
        - values-dev.yaml
        artifactOverrides:
          image: eshepelyuk/json2zk
        imageStrategy:
          helm: {}
- name: e2e
  deploy:
    helm:
      releases:
      - name: cmak-operator
        chartPath: .
        wait: true
        valuesFiles:
        - test/e2e/values-e2e.yaml
        artifactOverrides:
          image: eshepelyuk/json2zk
        imageStrategy:
          helm: {}
