cmak:
  clustersCommon:
    curatorConfig:
      zkMaxRetry: 100

  clusters:
    - name: "cluster-stage"
      kafkaVersion: "2.5.0"
      curatorConfig:
        zkConnect: "kafka01.stage:2181,kafka02.stage:2181"
    - name: "cluster-prod"
      enabled: false
      kafkaVersion: "2.1.0"
      curatorConfig:
        zkConnect: "kafka01.prod:2181,kafka02.prod:2181,kafka03.prod:2181"

zk:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

ui:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
