apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cmak.name" . }}-clusters
  labels:
    {{- include "cmak.labels" . | nindent 4 }}
data:
  clusters.yaml: |-
    {{- pick .Values "cmak" | toYaml | nindent 4 }}

