{{- $nm := include "cmak.name" . -}}
{{- $version := get (default (dict "tag" .Chart.Version) .Values.image) "tag" -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $nm }}-clusters
  labels:
    {{- include "cmak.labels" . | nindent 4 }}
spec:
  {{- if .Values.reconcile.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.reconcile.successfulJobsHistoryLimit }}
  {{- end }}
  {{- if .Values.reconcile.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.reconcile.failedJobsHistoryLimit }}
  {{- end }}
  schedule: {{ .Values.reconcile.schedule | quote }}
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: {{ $nm }}-clusters
              configMap:
                name: {{ $nm }}-clusters
          containers:
            - name: setup
              image: "eshepelyuk/cmak-operator-cli:{{ $version }}"
              command: ['python3', './json2zk.py']
              args:
                - '{{ .Values.reconcile.overwriteZk | ternary "--" "--no-" }}overwrite-zk'
                - '{{ $nm }}.{{ $.Release.Namespace }}:2181'
                - '/kafka-manager/configs'
                - '/opt/clusters'
              volumeMounts:
                - name: {{ $nm }}-clusters
                  mountPath: /opt/clusters
