{{- $nm := include "cmak.name" . -}}
{{- $dict := .Values.image | default (dict "tag" .Chart.Version "repository" (printf "%s/eshepelyuk/cmak2zk" .Values.imageRegistry)) -}}
{{- $image := printf "%s:%s" $dict.repository $dict.tag -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $nm }}-reconcile
  labels:
    {{- include "cmak.labels" . | nindent 4 }}
spec:
  {{- if .Values.reconcile.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.reconcile.successfulJobsHistoryLimit }}
  {{- end }}
  {{- if .Values.reconcile.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.reconcile.failedJobsHistoryLimit }}
  {{- end }}
  schedule: {{ .Values.reconcile.schedule | quote }}
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: {{ $nm }}-clusters
              configMap:
                name: {{ $nm }}-clusters
          containers:
            - name: setup
              image: {{ $image | quote }}
              command: ['python3', '/app/bin/cmak2zk.py']
              args:
                - '{{ .Values.reconcile.overwriteZk | ternary "--" "--no-" }}overwrite-zk'
                - '{{ $nm }}.{{ $.Release.Namespace }}:2181'
                - '/app/etc/clusters.yaml'
              volumeMounts:
                - name: {{ $nm }}-clusters
                  mountPath: /app/etc
