{{- if .Values.e2e }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "cmak.name" . }}
spec:
  entryPoints:
    - web
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ include "cmak.name" . }}
          port: 2181
{{- end }}
