{{- if .Values.ingress -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "cmak.name" . | quote }}
  labels:
    {{- include "cmak.labels" . | nindent 4 }}
{{- with .Values.ingress.annotations }}
  annotations:
  {{ . | toYaml | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ printf "%s-tls" .Values.ingress.host | replace "." "-" | quote }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path | quote }}
            backend:
              serviceName: {{ include "cmak.name" . | quote }}
              servicePort: {{ .Values.ui.port }}
{{- end }}
