{{ if .Values.ui.consumerPropertiesSsl }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cmak.name" . }}-ssl
  labels:
    {{- include "cmak.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.ui.consumerPropertiesSsl }}
  truststore: {{ .truststore.value }}
  keystore: {{ .keystore.value }}
  {{- end -}}
{{- end -}}
