{{ if .Values.ui.consumerPropertiesSsl }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cmak.name" . }}-ssl
  labels:
    {{- include "cmak.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.ui.consumerPropertiesSsl }}
  truststore: {{ .truststore.value }}
  keystore: {{ .keystore.value }}
  {{- end -}}
{{- end -}}
{{ if .Values.ui.authentication.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cmak.name" . }}-auth
  labels:
    {{- include "cmak.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ required "Please set ui.authentication.password" .Values.ui.authentication.password | b64enc | quote }}
{{- end -}}
