apiVersion: v1
kind: Service
metadata:
  name: {{ include "cmak.name" . }}
  labels:
    {{- include "cmak.labels" . | nindent 4 }}
  {{- with .Values.ui.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - name: zk
      port: 2181
      targetPort: zk
      protocol: TCP
    - name: http
      port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "cmak.selectorLabels" . | nindent 4 }}
