name: Build
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '*.puml'
      - '.github/workflows/release.yaml'
jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 20
      - uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc.yml
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: jaxxstorm/action-install-gh-release@v1
        with:
          repo: GoogleContainerTools/skaffold
          tag: v1.38.0
          cache: enable
          extension-matching: disable
          rename-to: skaffold
          chmod: 0755
      - uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: just test
      - uses: rinx/setup-k3d@v0.0.4
        with:
          skipClusterCreation: true
      - run: just k3d
      - run: just test-e2e

