name: Test

on:
  workflow_dispatch

jobs:
  test_job:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/core:2.9
        with:
          args: "--help"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: |
          gem install asciidoctor
      - run: |
          asciidoctor --version
          pandoc --version
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: "README2"
      #     path: "README2.md"

